<?php

/**
 * Lumen Authors API
 * サンプルです.   You can findout more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fendo181git@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Lumen Authors API
 * @version 1.0.0
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * get authorsGet
 * Summary: Get all author by id
 * Notes: 
 * Output-Formats: [application/json, application/xml]
 */
$app->get('/Fendo181/APP/1.0.0/authors', 'AuthorsApi@authorsGet');
/**
 * post authorsPost
 * Summary: Create an new author
 * Notes: 
 * Output-Formats: [application/json, application/xml]
 */
$app->post('/Fendo181/APP/1.0.0/authors', 'AuthorsApi@authorsPost');
/**
 * delete authorsIdDelete
 * Summary: Delete author by id
 * Notes: This can only be done by the logged in user.
 * Output-Formats: [application/json, application/xml]
 */
$app->delete('/Fendo181/APP/1.0.0/authors/{id}', 'AuthorsApi@authorsIdDelete');
/**
 * get authorsIdGet
 * Summary: Get an author by id
 * Notes: 
 * Output-Formats: [application/json, application/xml]
 */
$app->get('/Fendo181/APP/1.0.0/authors/{id}', 'AuthorsApi@authorsIdGet');
/**
 * put authorsIdPut
 * Summary: Updated author by id
 * Notes: Update Author info
 * Output-Formats: [application/json, application/xml]
 */
$app->put('/Fendo181/APP/1.0.0/authors/{id}', 'AuthorsApi@authorsIdPut');

